#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# [ ! -s ~/.config/mpd/pid ] && mpd

# For polkit-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Alternatively, if using lxsession
lxpolkit &

# Run custom look script
/home/omar/.local/bin/newlook

# Start network applets (uncomment if needed)
# nm-applet &
# blueman-applet &

# Start status bar
slstatus &

# Start compositor for transparency and effects
picom &
exec dwm
